server:
  port: 8082

#spring
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    active: dev

  session:
    store-type: none
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  cache:
    type: redis

  messages: #国际化
    basename: i18n/messages,i18n/ValidationMessages
  mvc: # 捕获404
    throw-exception-if-no-handler-found: true
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  aop: #使用CGLIB来实现AOP的时候
    proxy-target-class: true

  #DATABASE CONFIG
  datasource:
    #    Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    SqlServer
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    Oracle
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: config,stat,wall,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select count(*) from sys_user
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCYVbEFPqEMp6PGoHcTRLjOnFKSHMT3EGrxneHax7lHie0ZQcO3GNLsgLBWfUmSXb+geWsgM0A9vQ+g14QUbMfvjk82Ii3v5u3zbKoupudUbD/f+e6450DOtU5PBaIiALdB66+2M5SRJg57H5eLQ0I23RQ6cUyXHymVwURM72fvOwIDAQAB
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.publicKey}
  web:
    resources:
      static-locations: file:${oss.local.upload-file-path}

#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/sunseagear/wind/modules/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sunseagear.wind.modules.*.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      #主键类型 com.baomidou.mybatisplus.annotation.IdType";
      id-type: ASSIGN_ID
      #字段策略 com.baomidou.mybatisplus.annotation.FieldStrategy"
      select-strategy: NOT_EMPTY
      insert-strategy: NOT_EMPTY
      update-strategy: IGNORED
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    jdbc-type-for-null: 'null'
    #数据库大写下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #开启sql日志
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型

#  logging
logging:
  config: classpath:log/logback-${spring.profiles.active}.xml

#shiro
shiro:
  filter-chain-definitions: /json/oss/**=anon;/json/**=anon;/jcaptcha*=anon;/sso/oauth2/revoke_token=authc;/sso/oauth2/**=anon;/**=authc

#beetl配置
beetlsql:
  enabled: false


#文件上传配置
#使用的上传存储空间,local本地,aliyun:阿里云
oss:
  client-type: local
  #默认上传目录
  base_dir: userfiles
  #允许的文件扩展名
  allowed_extension: mp4,bmp, gif, jpg, jpeg, png,doc, docx, xls, xlsx, ppt, pptx,html,htm,txt,rar, zip, gz, bz2,pdf
  #最大文件大小 50M
  max_size: 52428800
  #是否需要按照日期存放文件
  needDatePath: false

#短信配置
sms:
  client-type: aliyun
  open: true
  sign-name: 飞廉
  aliyun:
    #阿里云api的密钥access key id
    access-key-id: 阿里云ID
    #阿里云api的密钥access key secret
    access-key-secret: 阿里云 key

#定时任务配置
quartz:
  open-cluster: false # 是否开启集群
  config-location: /quartz/quartz.properties # 集群配置文件路径
  data-source: qzDS # 集群数据库，使用当前数据库可以设置为空或者default

