import {
  Lazyload,
  Image as VanImage,
  Loading,
  Icon,
  Row,
  Col,
  Cell,
  CellGroup,
  Grid,
  GridItem,
  Button,
  NavBar,
  Field,
  Form,
  List,
  Tab,
  Tabs,
  Tabbar,
  TabbarItem,
  Swipe,
  SwipeItem,
  DropdownMenu,
  DropdownItem,
  Collapse,
  CollapseItem,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  NoticeBar,
  Uploader,
  PullRefresh,
  ActionSheet,
  Circle,
  DatetimePicker,
  Calendar,
  Popover,
  Switch,
  Toast,
  Popup,
  Dialog,
  Progress,
  Empty,
  Skeleton,
  CountDown,
  IndexBar,
  IndexAnchor
} from 'vant'

export default {
  install: Vue => {
    Vue.use(Lazyload)
    Vue.use(VanImage)
    Vue.use(Loading)
    Vue.use(Row)
    Vue.use(Col)
    Vue.use(Cell)
    Vue.use(CellGroup)
    Vue.use(Grid)
    Vue.use(GridItem)
    Vue.use(Button)
    Vue.use(NavBar)
    Vue.use(Field)
    Vue.use(Form)
    Vue.use(List)
    Vue.use(Tab)
    Vue.use(Tabs)
    Vue.use(Tabbar)
    Vue.use(TabbarItem)
    Vue.use(Swipe)
    Vue.use(SwipeItem)
    Vue.use(DropdownMenu)
    Vue.use(DropdownItem)
    Vue.use(Collapse)
    Vue.use(CollapseItem)
    Vue.use(Radio)
    Vue.use(RadioGroup)
    Vue.use(Checkbox)
    Vue.use(CheckboxGroup)
    Vue.use(NoticeBar)
    Vue.use(Uploader)
    Vue.use(Icon)
    Vue.use(PullRefresh)
    Vue.use(ActionSheet)
    Vue.use(Circle)
    Vue.use(DatetimePicker)
    Vue.use(Calendar)
    Vue.use(Popover)
    Vue.use(Switch)
    Vue.use(Toast)
    Vue.use(Popup)
    Vue.use(Dialog)
    Vue.use(Progress)
    Vue.use(Empty)
    Vue.use(Skeleton)
    Vue.use(CountDown)
    Vue.use(IndexBar)
    Vue.use(IndexAnchor)
  }
}

