export { default as MatchItem } from './matchItem.vue'
export { default as NewsItem } from './newsItem.vue'
export { default as RecommendItem } from './recommendItem.vue'
export { default as Instant } from './Instant.vue'
export { default as Top } from './Top.vue'
export { default as Shooter } from './Shooter.vue'
export { default as LmSelect } from './select.vue'
